name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      uses: pnpm/action-setup@v4.0.0
      with:
        # Version of pnpm to install
        version: 9.6.0 # optional
        # Where to store pnpm files
        # dest: # optional, default is ~/setup-pnpm
        # If specified, run `pnpm install`
        # run_install: # optional, default is null
        # File path to the package.json to read "packageManager" configuration
        # package_json_file: # optional, default is package.json
        # When set to true, @pnpm/exe, which is a Node.js bundled package, will be installed, enabling using pnpm without Node.js.
        # standalone: # optional, default is false

    - name: Build
      run: |
        pnpm run build:tsc

    - name: Run
      run: |
        pnpm run start:prod
